-- I'll fix this up some other time
-- local root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1])
-- local jdtls_path = vim.fn.exepath("jdtls")
-- local project_name = vim.fn.fnamemodify(root_dir, ":p:h:t")
-- local data_dir = vim.fn.expand("$HOME/.cache/nvim/jdtls/workspaces") .. project_name
--
-- local config = {
-- 	cmd = {
-- 		"java",
-- 		"-Declipse.application=org.eclipse.jdt.ls.core.id1",
-- 		"-Dosgi.bundles.defaultStartLevel=4",
-- 		"-Declipse.product=org.eclipse.jdt.ls.core.product",
-- 		"-Dlog.protocol=true",
-- 		"-Dlog.level=ALL",
-- 		"-Xmx1g",
-- 		"-javaagent:" .. jdtls_path .. "/lombok.jar",
-- 		"--add-modules=ALL-SYSTEM",
-- 		"--add-opens",
-- 		"java.base/java.util=ALL-UNNAMED",
-- 		"--add-opens",
-- 		"java.base/java.lang=ALL-UNNAMED",
-- 		"-jar",
-- 		vim.fn.glob(jdtls_path .. "/plugins/org.eclipse.equinox.launcher_*.jar"),
-- 		"-configuration",
-- 		jdtls_path .. "/config_linux",
-- 		"-data",
-- 		data_dir,
-- 	},
-- 	root_dir = root_dir,
-- }
--
-- return {
-- 	"nvim-jdtls",
-- 	ft = "java",
-- 	after = function()
-- 		require("jdtls").start_or_attach(config)
-- 	end,
-- }
